// Generated by CoffeeScript 1.10.0



SpeechBlocks.Interpreter = function(controller) {
  this.controller = controller;
}

SpeechBlocks.Interpreter.prototype.interpret = function(command) {
  if (command.action === "Run") {
    return run(command);
  } else if (command.action === "Add") {
    return addBlock(command);
  } else if (command.action === "Move") {
    return moveBlock(command);
  } else if (command.action === "Modify") {
    return modifyBlock(command);
  } else if (command.action === "Delete") {
    return deleteBlock(command);
  }
};

SpeechBlocks.Interpreter.prototype.run = function(command) {
  Blockly.JavaScript.addReservedWords('code');
  var code = Blockly.JavaScript.workspaceToCode(workspace);
  try {
    eval(code);
  } catch (e) {
    alert(e);
  }
};

SpeechBlocks.Interpreter.prototype.addBlock = function(command) {
  controller.addBlock(command.type, id++, new SpeechBlocks.translation(0,0));
};

SpeechBlocks.Interpreter.prototype.moveBlock = function(command) {
  controller.moveBlock(command.block.number, command.where);
};

SpeechBlocks.Interpreter.prototype.modifyBlock = function(command) {};

SpeechBlocks.Interpreter.prototype.deleteBlock = function(command) {
  controller.removeBlock(command.block.number);
};
