// Generated by CoffeeScript 1.10.0
describe('Parser', function() {
  var parser;
  parser = new Parser();
  it('can recognize run commands', function() {
    expect(parser.parse("run it").name).toBe("Run");
    return expect(parser.parse("run the program").name).toBe("Run");
  });
  return it('can recognize add a blue block', function() {
    expect(parser.parse("add a blue block").name).toBe("Move");
    expect(parser.parse("add a blue block").what.name).toBe("New Block");
    return expect(parser.parse("add a blue block").what.color).toBe("blue");
  });
});
